name: CI Workflow 

  on:
   push:
     branches: 
       -main
    pull_request:

  jobs: 
    tests: 
      runs-on:ubuntu-latest

      steps:
        -name: Checkout Code
          uses: actions/checkout@v3

          

    
